---
# install and setup all necessary roles locally
- hosts: localhost
  serial: 1

  tasks:
    - name: Create roles directory
      file:
        path: roles
        state: directory

    - name: Install roles from requirements.yml to roles/
      local_action: command ansible-galaxy install -fr requirements.yml --roles-path roles

    - name: add roles dir to .gitignore
      lineinfile:
        dest: .gitignore
        regexp: '^\/roles$'
        line: '/roles'
        state: present

# after variable input, run all roles necessary to deploy and run (out of box)
# WordPress instance (3 separate containers running WordPress PHP7 FPM, Nginx and MariaDB)
- hosts: aws-wp

  vars_files:
    - defaults/main.yml

  remote_user: "{{ system_user }}"
  become: yes
  gather_facts: no
  serial: 2

  vars_prompt:

    - name: domain
      prompt: "\n------
              \n\nSpecify blog URL"
      private: no
      default: "foolcontrol.org"

    - name: wp_version
      prompt: "\n------
              \n\nSpecify WordPress version you'd like to use"
      private: no
      default: "4.7.5"

    - name: wp_db_name
      prompt: "\n------
              \n\nSpecify WordPress database name"
      private: no
      default: "wordpress"

    - name: wp_db_tb_pre
      prompt: "\n------
              \n\nSpecify WordPress table prefix"
      private: no
      default: "wp_"

    - name: wp_db_host
      prompt: "\n------
              \n\nSpecify WordPress host"
      private: no
      default: "mysql"

    - name: wp_db_psw
      prompt: "\n------
              \n\nSpecify WordPress database password"
      private: yes
      default: "change-M3"
      confirm: yes

  roles:
  - AdnanHodzic.python-ubuntu-bootstrap
  - AdnanHodzic.system-upgrade
  - AdnanHodzic.docker-compose-setup
  - AdnanHodzic.containerized-wordpress
