---
# install and setup all necessary roles
- hosts: localhost
  serial: 1

  tasks:
    - name: Create roles directory
      file:
        path: roles
        state: directory

    - name: Install roles from requirements.yml to roles/
      local_action: command ansible-galaxy install -fr requirements.yml --roles-path roles

    - name: add roles dir to .gitignore
      lineinfile:
        dest: .gitignore
        regexp: '^\/roles$'
        line: '/roles'
        state: present

# run all roles on new host
- hosts: aws-wp

  vars_files:
    - defaults/main.yml

  remote_user: "{{ system_user }}"
  become: yes
  gather_facts: no
  serial: 2

  roles:
  - AdnanHodzic.python-ubuntu-bootstrap
  - AdnanHodzic.system-upgrade
  - AdnanHodzic.docker-compose-setup
  - AdnanHodzic.containerized-wordpress
