---
# This playbook which will call all necessary roles to deploy Docker Compose
# project for WordPress blog. Consisting of 3 separate containers running:
# WordPress PHP7 FPM, Nxing and MariaDB

# ToDo:
#
# automatically install requirements (prior to tasks section)
# manage variables thru vars_prompt?
# add variables for (from defaults/main.yml):
#  * db config
#  * wordpress (since there's no latest tag)
#
#  * upon testing successful pick of variables from defaults
#    verify one last time if this is possible with vars_prompt

# run as part of pre_tasks section
- hosts: aws-wp

  vars_files:
    - defaults/main.yml

  remote_user: "{{ system_user }}"
  become: yes
  gather_facts: no
  serial: 1

  roles:
    - { role: AdnanHodzic.python-ubuntu-bootstrap }

- hosts: aws-wp
  remote_user: "{{ system_user }}"
  become: yes

# run as part of tasks section
  roles:
    - { role: AdnanHodzic.system-upgrade }
    - { role: AdnanHodzic.docker-compose }
    - { role: AdnanHodzic.wordpress-docker }
