# Roles required for "project-deploy.yml" playbook to run all defined roles.
#
# install by running:
# ansible-galaxy install -r requirements.yml

- name: AdnanHodzic.python-ubuntu-bootstrap
  src: https://github.com/AdnanHodzic/ansible-role-python-ubuntu-bootstrap
  version: master

- name: AdnanHodzic.system-upgrade
  src: https://github.com/AdnanHodzic/ansible-role-system-upgrade
  version: master

- name: AdnanHodzic.docker-compose
  src: https://github.com/AdnanHodzic/ansible-role-docker-compose
  version: master

- name: AdnanHodzic.wordpress-docker-deploy
  src: https://github.com/AdnanHodzic/ansible-role-wordpress-docker-deploy
  version: master
