- name: AdnanHodzic.python-ubuntu-bootstrap
  src: https://github.com/AdnanHodzic/ansible-role-python-ubuntu-bootstrap
  version: master

- name: AdnanHodzic.system-upgrade
  src: https://github.com/AdnanHodzic/ansible-role-system-upgrade
  version: master

- name: AdnanHodzic.docker-compose-setup
  src: https://github.com/AdnanHodzic/ansible-role-docker-compose-setup
  version: master

- name: AdnanHodzic.containerized-wordpress
  src: https://github.com/AdnanHodzic/ansible-role-containerized-wordpress
  version: master
